version: "3.8"

services:

  combine-mes:
    image: johnamcruz/algotraderai:latest
    container_name: algo-combine-mes
    volumes:
      - ./logs:/app/logs
      - ./configs:/app/configs:ro
    command: --config /app/configs/combine-mes.yaml
    restart: unless-stopped

  practice-mnq:
    image: johnamcruz/algotraderai:latest
    container_name: algo-practice-mnq
    volumes:
      - ./logs:/app/logs
      - ./configs:/app/configs:ro
    command: --config /app/configs/practice-mnq.yaml
    restart: unless-stopped

  practice-mes:
    image: johnamcruz/algotraderai:latest
    container_name: algo-practice-mes
    volumes:
      - ./logs:/app/logs
      - ./configs:/app/configs:ro
    command: --config /app/configs/practice-mes.yaml
    restart: unless-stopped
